### ISSUE TITLE
Variable out of scope

### ISSUE THREAD

**Issue by KevinCooper** [mattmcvicar/SuMoTED#1]
In the function tree_files_to_adjacency_matrices, line 234 is called with the arguments

`
is_tree(A, complete_labels, tree_file)
`

However, tree_file is not in scope at this line.

**Comment by mattmcvicar** [comment]
Hi Kevin, thanks for spotting this. It seems like it was finding `tree_file` from the scope of the function, which is somewhat dodgy....I've pushed a commit just now which makes this explicit. Could you try now? If it still doesn't work for you could you upload your data for me to try?

**Comment by KevinCooper** [comment]
Thank you!
